<a href="https://colab.research.google.com/github/Faherme46/Practica/blob/main/Parcial_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Dataset Creation**

In [ ]:
# the library is imported to be able to use it later
import pandas as pd
import numpy as np


In [117]:
# loading dataset and make a first overview
ruta = "/content/Turismo_Receptivo_en_el_Valle_del_Cauca.csv"
datos = pd.read_csv(ruta)



In [118]:
# Create a DataFrame with data
df = pd.DataFrame(datos)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1703 entries, 0 to 1702
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   GENERO                    1703 non-null   object
 1   PAÍS DE PROCEDENCIA       1703 non-null   object
 2   DEPARTAMENTO              1703 non-null   object
 3   RANGO EDAD                1702 non-null   object
 4   MOTIVO VIAJE              1703 non-null   object
 5   NOCHES                    1695 non-null   object
 6   TIPO ALOJAMIENTO          1703 non-null   object
 7   GASTO TURISTICO GENERADO  1703 non-null   int64 
 8   MEDIO                     1703 non-null   object
 9   AÑO                       1703 non-null   int64 
dtypes: int64(2), object(8)
memory usage: 133.2+ KB



# **Data selection**

studying the data set, we find that it is good for our purpose. The data is structured, the size is appropriate for the process and is relevant to our mission

In the previous entry we can find that there is not much missing data, this will be quite useful for our purpose.
The colums whith missing data are "Noches" and "Rango edad". Go to review to evaluate if is necesary and possible delete the columns.


We must do a review of the entries

In [119]:
df_ordenado = df.sort_values(by='PAÍS DE PROCEDENCIA')
df_ordenado.head()

GENERO PAÍS DE PROCEDENCIA     DEPARTAMENTO RANGO EDAD  \
105   MASCULINO           ARGENTINA  SIN INFORMACION      27-38   
205    FEMENINO           ARGENTINA  SIN INFORMACION      27-38   
439    FEMENINO           ARGENTINA  SIN INFORMACION      27-38   
919    FEMENINO              BRASIL  SIN INFORMACION      39-50   
1512   FEMENINO              BRASIL  SIN INFORMACION      39-50   

                         MOTIVO VIAJE NOCHES          TIPO ALOJAMIENTO  \
105   VISITAR A FAMILIARES Y/O AMIGOS     10                     HOTEL   
205   VISITAR A FAMILIARES Y/O AMIGOS      4                     HOTEL   
439   VISITAR A FAMILIARES Y/O AMIGOS      4                     HOTEL   
919         VACACIONES, RECREO Y OCIO     30  CASA FAMILIARES / AMIGOS   
1512        VACACIONES, RECREO Y OCIO     30  CASA FAMILIARES / AMIGOS   

      GASTO TURISTICO GENERADO                   MEDIO   AÑO  
105                    6000000  AMIGOS Y/O FAMILIARES.  2021  
205                    5000000  AMIGOS Y/O FAMILIARES.  2021  
439                    5000000  AMIGOS Y/O FAMILIARES.  2021  
919                    3000000          YA LOS CONOCÍA  2022  
1512                   6000000          YA LOS CONOCÍA  2022

It can be seen that the department column does not apply to countries other than Colombia, therefore it can be removed from the dataset

In [120]:
try:
  df=df.drop(['DEPARTAMENTO'],axis=1)
except:
  print("Ya fue borrado")

In [121]:
#update and review the end of dataset
df_ordenado = df.sort_values(by='PAÍS DE PROCEDENCIA')
df_ordenado.tail(50)

GENERO PAÍS DE PROCEDENCIA       RANGO EDAD  \
949    FEMENINO     SIN INFORMACION            39-50   
950    FEMENINO     SIN INFORMACION            39-50   
951   MASCULINO     SIN INFORMACION            39-50   
1100  MASCULINO     SIN INFORMACION            39-50   
1175   FEMENINO     SIN INFORMACION            27-38   
712    FEMENINO     SIN INFORMACION  SIN INFORMACION   
1207   FEMENINO     SIN INFORMACION            15-26   
1324  MASCULINO     SIN INFORMACION            27-38   
745   MASCULINO     SIN INFORMACION            39-50   
1380   FEMENINO     SIN INFORMACION  SIN INFORMACION   
966   MASCULINO     SIN INFORMACION            27-38   
554    FEMENINO     SIN INFORMACION            27-38   
813   MASCULINO     SIN INFORMACION            15-26   
551   MASCULINO     SIN INFORMACION            27-38   
1145   FEMENINO     SIN INFORMACION            27-38   
1204   FEMENINO     SIN INFORMACION            27-38   
725   MASCULINO     SIN INFORMACION            27-38   
1592  MASCULINO     SIN INFORMACION            27-38   
1591   FEMENINO     SIN INFORMACION            39-50   
1590  MASCULINO     SIN INFORMACION            39-50   
675    FEMENINO     SIN INFORMACION            39-50   
953    FEMENINO     SIN INFORMACION            39-50   
1674  MASCULINO               SUIZA            39-50   
1439   FEMENINO               SUIZA            39-50   
1676  MASCULINO               SUIZA            27-38   
809   MASCULINO           VENEZUELA        mas de 63   
352    FEMENINO           VENEZUELA            15-26   
472    FEMENINO           VENEZUELA            15-26   
278   MASCULINO           VENEZUELA            27-38   
283   MASCULINO           VENEZUELA            27-38   
235    FEMENINO           VENEZUELA            15-26   
298    FEMENINO           VENEZUELA            15-26   
227    FEMENINO           VENEZUELA            15-26   
304   MASCULINO           VENEZUELA            15-26   
305    FEMENINO           VENEZUELA            15-26   
219   MASCULINO           VENEZUELA            27-38   
218   MASCULINO           VENEZUELA            39-50   
1241  MASCULINO           VENEZUELA            27-38   
317    FEMENINO           VENEZUELA            27-38   
201    FEMENINO           VENEZUELA            15-26   
1113  MASCULINO           VENEZUELA            39-50   
354    FEMENINO           VENEZUELA            15-26   
355   MASCULINO           VENEZUELA            15-26   
1299  MASCULINO           VENEZUELA  SIN INFORMACION   
369    FEMENINO           VENEZUELA            27-38   
370   MASCULINO           VENEZUELA            27-38   
390    FEMENINO           VENEZUELA            27-38   
476   MASCULINO           VENEZUELA            27-38   
202   MASCULINO           VENEZUELA            27-38   
441    FEMENINO           VENEZUELA            27-38   

                                           MOTIVO VIAJE           NOCHES  \
949                           VACACIONES, RECREO Y OCIO               30   
950                           VACACIONES, RECREO Y OCIO               30   
951                           VACACIONES, RECREO Y OCIO               30   
1100  ASISTIR A EVENTOS DEPORTIVOS COMO DEPORTISTA O...               15   
1175                          VACACIONES, RECREO Y OCIO                6   
712                           VACACIONES, RECREO Y OCIO  SIN INFORMACION   
1207                    VISITAR A FAMILIARES Y/O AMIGOS                2   
1324                          VACACIONES, RECREO Y OCIO                4   
745                           VACACIONES, RECREO Y OCIO                5   
1380                    VISITAR A FAMILIARES Y/O AMIGOS                6   
966                           VACACIONES, RECREO Y OCIO               30   
554                     VISITAR A FAMILIARES Y/O AMIGOS                8   
813                     VISITAR A FAMILIARES Y/O AMIGOS                8   
551                           VACACIONES, RECREO Y OCIO                6   
1145        

We have seen that there are boxes labeled "SIN INFORMACION" which indicates that there is much more missing data than we thought. Therefore, we are going to replace the "SIN INFORMACION" data with NaN entries so that the library can detect them.

In [122]:
#REPLACE DATA AND REVIEW
df=df.replace('SIN INFORMACION', np.nan)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1703 entries, 0 to 1702
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   GENERO                    1702 non-null   object
 1   PAÍS DE PROCEDENCIA       1649 non-null   object
 2   RANGO EDAD                1653 non-null   object
 3   MOTIVO VIAJE              1629 non-null   object
 4   NOCHES                    1547 non-null   object
 5   TIPO ALOJAMIENTO          1556 non-null   object
 6   GASTO TURISTICO GENERADO  1703 non-null   int64 
 7   MEDIO                     1702 non-null   object
 8   AÑO                       1703 non-null   int64 
dtypes: int64(2), object(7)
memory usage: 119.9+ KB


The PAIS DE PROCEDENCIA  column is not very related to the model we want to develop, therefore we are going to discard this.
We will also discard column MEDIO as its relevance to the model is very low.

In [123]:
#order to delete the columns
try:
  df=df.drop(['MEDIO'],axis=1)    
  df=df.drop(['PAÍS DE PROCEDENCIA'],axis=1)
  
except:
  print("Ya fueron borrados")    



We believe that currently gender is not an issue that affects a person's tourist capacity, as well as their reasons for traveling. therefore we will discard the GENERO column

In [124]:
#order to delete the columns
try:
  df=df.drop(['GENERO'],axis=1)    
    
except:
  print("Ya fueron borrados")  

# **Data Cleaning**

We will proceed to do the necessary cleaning of the data to continue

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1703 entries, 0 to 1702
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   RANGO EDAD                1653 non-null   object
 1   MOTIVO VIAJE              1629 non-null   object
 2   NOCHES                    1547 non-null   object
 3   TIPO ALOJAMIENTO          1556 non-null   object
 4   GASTO TURISTICO GENERADO  1703 non-null   int64 
 5   AÑO                       1703 non-null   int64 
dtypes: int64(2), object(4)
memory usage: 80.0+ KB


In [126]:
#we want to find the missing data in the most important columns
resultado = df.loc[(df['TIPO ALOJAMIENTO'].isnull()) & (df['MOTIVO VIAJE'].isnull()) & (df['NOCHES'].isnull())]
resultado.head(100)

RANGO EDAD MOTIVO VIAJE NOCHES TIPO ALOJAMIENTO  \
415       27-38          NaN    NaN              NaN   
456       27-38          NaN    NaN              NaN   
1129        NaN          NaN    NaN              NaN   

      GASTO TURISTICO GENERADO   AÑO  
415                     600000  2021  
456                     700000  2021  
1129                         0  2022

I see that rows 415, 456 and 1129  has almost all the data missing, so I'll delete it from the dataset to remove the noise.

In [127]:
#order to delete the rows
try:
  df = df.drop(1129)
  df = df.drop(456)
  df = df.drop(415)
except:
  print("ya fueron borrados")


# **Data Transformation**
After performing the data cleaning, we are going to do the necessary transformation to establish the model

In [ ]:
#create an auxiliar DataFrame to make the Transformation
df_transform=df